name: bepop_fitness
description: Bepop Fitness is a mobile app for fitness enthusiasts. It helps users to stay fit and healthy by providing them with a variety of exercises and workouts.

publish_to: 'none'

version: 1.0.0+1.2

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:

  flutter:
    sdk: flutter

  #Basic
  cupertino_icons: 1.0.8
  cached_network_image: 3.4.1
  google_fonts: 6.3.2
  intl: 0.20.2
  flutter_vector_icons: 2.0.0
  lottie: 3.3.1
  device_preview: 1.2.0

  flutter_chrome_cast:
    path: flutter_google_cast-master


  #Network
  http: 1.4.0
  connectivity_plus: 7.0.0

  #State Management
  mobx: 2.5.0
  flutter_mobx: 2.3.0

  flutter_inappwebview: 6.1.5

  #Storage
  shared_preferences: 2.5.3

  audioplayers: 6.5.1


  flutter_staggered_grid_view: 0.7.0


  #calendar
  table_calendar: 3.2.0

  syncfusion_flutter_datepicker: 26.2.14

  circular_countdown_timer: 0.2.4
  device_info_plus: 12.1.0
  animated_background: 2.0.0
  top_snackbar_flutter: 3.3.0

  # Firebase
  firebase_core: 3.15.2
  firebase_analytics: 11.6.0
  firebase_crashlytics: 4.3.10
  firebase_auth: 5.7.0
  firebase_storage: 12.4.10
  firebase_messaging: 15.2.10
  cloud_firestore: 5.6.12
  file_picker: 8.3.7
  paginate_firestore:
    git:
      url: https://github.com/waqadArshad/paginate_firestore.git

  #login
  google_sign_in: 6.3.0
  the_apple_sign_in: 1.1.1


  flutter_toggle_tab: 1.4.1

  #one signal
  onesignal_flutter: 5.3.4

  #notification
  awesome_notifications: 0.10.1

  #OTP
  pinput: 5.0.2

  #Video player
  youtube_player_flutter: 9.1.2
  chewie: 1.8.1
  fetch_client: 1.1.1
  video_player: 2.10.0


  #ads
  google_mobile_ads: 5.3.1

  #step count
  pedometer: 4.1.1
  health: 13.2.0

  #gpt
  chat_gpt_flutter: 1.0.16
  chat_gpt_sdk: 3.1.2


  #Other
  marquee: 2.3.0
  fluttertoast: 8.2.14
  country_code_picker: 3.4.0
  infinite_listview: 1.1.0
  html: 0.15.4
  url_launcher: 6.3.2
  image_picker: 1.2.0
  permission_handler: 12.0.1
  flutter_html:
    git:
      url: https://github.com/appmeetmighty/flutter_html.git
  flutter_tts: 4.2.3
  draggable_bottom_sheet: 1.0.2
  share_plus: 10.1.4
  flutter_time_picker_spinner: 2.0.0
  flutter_bounce: 1.1.0
  card_swiper: 3.0.1
  simple_pip_mode: 0.8.0
  photo_view: 0.15.0
  tuple: 2.0.2

  flutter_math_fork: 0.7.4
  focused_menu: 1.0.5
  font_awesome_flutter: 10.9.1
  smooth_page_indicator: 1.2.1
  dotted_border: 2.1.0
  photo_manager: 3.7.1
  wechat_assets_picker: 9.8.0
  image: 4.5.4
  palette_generator: 0.3.3+7

  #localizations
  flutter_localizations:
    sdk: flutter

  #chart
  syncfusion_flutter_charts: 26.2.14
  path_provider: 2.1.5
  #sizer: ^3.0.2

  crisp_chat: 2.4.1

  animated_text_kit: 4.2.3

  stripe_platform_interface: 11.3.0

  #payment
 # razorpay_flutter: ^1.3.7
  razorpay_flutter: 1.4.0
  flutter_stripe: 11.3.0
  bambara_flutter: 0.0.6
  pay_with_paystack: 1.0.14
  flutter_braintree_payment: 1.1.0

  flutter_paytabs_bridge: 2.7.2
  my_fatoorah_payment_flutter: 1.1.3
  video_compress: 3.1.4
  package_info_plus: 8.3.1
  readmore: 3.0.0
  visibility_detector: 0.4.0+2


dependency_overrides:
  intl: 0.18.1
  http: 0.13.6
  flutter_svg: 1.1.6
  flutter_layout_grid: 2.0.8
  webview_flutter: 4.13.0
  cloud_firestore: 5.6.12
  fading_edge_scrollview: 4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 2.8.0
  mobx_codegen: 2.7.4
  #flutter packages pub run build_runner build --delete-conflicting-outputs
  flutter_lints: 4.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/Flag/
    - assets/sounds/coins.mp3
    - assets/sounds/wrong.mp3
    - assets/sounds/startplay.mp3
    - assets/loading.json
